### ISSUE TITLE
Feature Request - Add more servers, 5 isn't enough.

### ISSUE THREAD

**Issue by opium-dev** [Loudbooks/Minecraft-Server-Installer#2]
So basically if you want a lot of people to use your application, you must add more features right?

What easier way is there to do that than just adding more server types?

Here are some suggestions

Modded
 - Magma [https://magmafoundation.org](url) Description: Forge with plugins
 - Sponge [https://spongepowered.org](url) Description: <>
 - MohistMC [https://mohistmc.com](url) Description: Minecraft Forge Server Software Implementing Paper/Spigot/Bukkit API
 - Arclight [https://github.com/IzzelAliz/Arclight](url) Description: A Bukkit(1.19/1.20) server implementation on Forge using Mixin.

Modern
 - Purpur [https://purpurmc.org](url) Description: Purpur is a drop-in replacement for Paper servers designed for configurability and new, fun, exciting gameplay features.
 - Tuinity [https://github.com/Tuinity/Tuinity](url) Description: Fork of Paper to improve performance without behavioural changes.
 - Spigot [https://www.spigotmc.org](url) Description: <>
 - CraftBukkit [https://getbukkit.org](url) Description: <>

Legacy
 - FluxSpigot [https://github.com/VictorML11/FluxSpigot](url) Description: PVP Based Jar
 - SportPaper [https://github.com/Electroid/SportPaper](url) Description: PVP & Cannoning Based Jar

Proxies
 - Veloctiy [https://papermc.io/software/velocity](url) Description: Velocity is the modern, high-performance proxy.
 - Travertine [https://papermc.io/downloads/all#Travertine](url) Description: <>
 - Bungeecord [https://www.spigotmc.org/wiki/bungeecord/](url) Description: BungeeCord is a useful software which acts as a proxy between the player's client and the connected Minecraft servers.
 - Waterfall [https://papermc.io/downloads/waterfall](url) Description: Download Waterfall, a Bungee-compatible upgrade, offering better performance and full compatibility.

Protocol Translators
 - GeyserMC [https://geysermc.org](url) Description: Allows bedrock players to join your server.

Other?
 - Glowstone [https://glowstone.net](url) Description: Glowstone is a completely open source Minecraft server that doesn't rely on any of Mojang's code

**Comment by Loudbooks** [comment]
To Do List: (In order)
- [ ] Bungeecord
- [ ] Velocity
- [ ] Waterfall
- [ ] GeyserMC
- [ ] Tuinity
- [ ] Glowstone
- [ ] Minestom

Not Happening: (https://essentialsx.net/do-not-use-mohist.html#)
- Magma
- Sponge
- Mohist
- Arclight

The rest may be done at a later date, I will think about it.

**Comment by Loudbooks** [comment]
Release will be coming out soon after more thorough testing is complete
